### ISSUE TITLE
Unable to commit since v1.1.0

### ISSUE THREAD

**Issue by gdowmont** [IAreKyleW00t/verified-bot-commit#103]
Hi,

Since version v1.1.0 the action is unable to complete the commit with different errors:

No files changed:
![Image](https://github.com/user-attachments/assets/19ecff4d-458f-46e7-83d8-c78621776cc7)

Changed files:

![Image](https://github.com/user-attachments/assets/f79151f5-4f3f-4a47-bc82-87e266688da8)

Reverting back to v.1.0.15 works fine on the same files.

Sample pipeline:
`name: Docs

permissions:
  contents: write

on:
  workflow_call:

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4

      - name: Terraform init
        id: init
        run: |
          echo "Running terraform init..."
          terraform init

      - name: Render terraform docs inside for components in the README.md
        id: components-docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          recursive: "true"
          output-file: README.md
          git-push: "false"
          config-file: .terraform-docs-components.yml

      - name: Render terraform docs inside for modules in the README.md
        id: modules-docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          recursive: "true"
          output-file: README.md
          git-push: "false"
          config-file: .terraform-docs-modules.yml

      - name: Commit changes
        id: commit
        uses: iarekylew00t/verified-bot-commit@v1.0.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          message: "terraform-docs: automated action"
          files: |
            *.md
`

**Comment by IAreKyleW00t** [comment]
Hey, thanks for reporting this - that’s pretty strange behavior and wasn’t something that came up in all my testing.

The “No blobs” error can probably be improved since no file changes isn’t necessarily an “error” anymore. I should add a test for that too.

For your 2nd error - is this running against a fork? I’m wondering if the Git operation to get a list of files can’t run against those, which was new to v1.1

**Comment by gdowmont** [comment]
Hey. Thanks for checking.

No, it runs inside PR against a branch of the same repo. Can't share the link as it is private.

But if there is any debug I can provide, happy to help.

**Comment by IAreKyleW00t** [comment]
Gotcha, well that rules that out. Hm, that’s definitely a bit strange then. Initial searching indicates this could be a permission issue with the local Git DB, where a previous step (somehow) writes to it with the incorrect permissions.

I’ll spend some time trying to reproduce the error later today. In the meantime if you want to try running `sudo chmod -R ugo+rwX .` **before** running the Action, that can help rule that out.

**Comment by IAreKyleW00t** [comment]
To support that claim, the [terraform-docs/gh-actions](https://github.com/terraform-docs/gh-actions) Action that you use is a Docker Action which runs as `root` and performs some `git` operations that may be preventing other non-root `git` operations from working.

https://github.com/terraform-docs/gh-actions/blob/main/src/docker-entrypoint.sh#L56-L65

**Comment by IAreKyleW00t** [comment]
I created a test repo with a dummy Terraform module so I can use those same Actions and can confirm that the permissions being messed up by that Action are the cause.

- [Test before v1.1](https://github.com/IAreKyleW00t/commit-test/pull/1)
- [Test after v1.1](https://github.com/IAreKyleW00t/commit-test/pull/2)
- [Test after v1.1 w/ permission fix](https://github.com/IAreKyleW00t/commit-test/pull/4)

You can see in the run with the permission fix that the owner of some `.git` files are not correct

```sh
$ ls -l .git
-rw-r--r--  1 runner docker    0 Mar 31 16:16 FETCH_HEAD
-rw-r--r--  1 runner docker   22 Mar 31 16:16 HEAD
-rw-r--r--  1 runner docker  423 Mar 31 16:16 config
-rw-r--r--  1 runner docker   83 Mar 31 16:16 config.worktree
-rwxr-xr-x  1 runner docker   73 Mar 31 16:16 description
drwxr-xr-x  2 runner docker 4096 Mar 31 16:16 hooks
-rw-r--r--  1 root   root    818 Mar 31 16:16 index
drwxr-xr-x  2 runner docker 4096 Mar 31 16:16 info
drwxr-xr-x  3 runner docker 4096 Mar 31 16:16 logs
drwxr-xr-x 18 runner docker 4096 Mar 31 16:16 objects
drwxr-xr-x  5 runner docker 4096 Mar 31 16:16 refs
-rw-r--r--  1 runner docker   41 Mar 31 16:16 shallow
```

Running this **after** the terraform-docs Action will fix it for all possible future `git` operations for any Action.

```sh
sudo chmod -R ugo+rwX .git
```

I could incorporate this into this Action so that it auto-fixes any permission errors, but that could be considered out-of-scope for an Action like this. What are your thoughts on this? I'll at least document this in the README so others are aware.

**Comment by gdowmont** [comment]
Hey. Thanks for all the testing. 

I think just adding a note to readme should be enough, since it won't interfere with how your action works or how others might have incorporated it.

Unless you feel like extending the action with a flag to set the permissions is worth the effort?

Just really curious about what changed between the versions to start causing it. Looking at the diff nothing really jumps out at me.

**Comment by IAreKyleW00t** [comment]
Also here is an alternative command that will keep the file permissions the same but just correct the User/Group to be the current user. Not sure why the other one was suggested - both work, but figured I'd share.

```sh
sudo chown -R "$(id -u):$(id -g)" .git
```

**Comment by IAreKyleW00t** [comment]
`v1.3.1` is out with the additional input to control the behavior of the Action when no commit is made. By default it will just show a `warning` since users are probably intending for something to be commit when they use it, so it's probably worth calling it out if nothing is added, but still maintain not failing. Users can opt to having `error` out, or ignore it with `info`.

The README is also updated with a [Common Errors](https://github.com/IAreKyleW00t/verified-bot-commit?tab=readme-ov-file#common-errors) section.

I'm gonna close this out, but feel free to re-open it (or make a new one) if you have any further questions or issues!

Thanks again for reporting this and helping me make this better.

**Comment by gdowmont** [comment]
Thanks for the suggestions and the new release

I tried to look for more info and actually discovered this https://github.com/terraform-docs/gh-actions/issues/50 which matches the behaviour we are seeing; apparently using PAT token would have fixed the initial problem with verified commits but using PAT tokens isn't really a best practice, if you can avoid them.

I have refactored my pipeline to avoid using their action (it has been some time since it had any updates anyway) and just install the binary directly. That made the rest of the git operations compatible with your amazing action without having to mess with the permissions.

Adding it here in case someone hits the same problem I had.

```
name: Docs

permissions:
  contents: write

on:
  workflow_call:

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Terraform with specified version on the runner
        run: |
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.19.0/terraform-docs-v0.19.0-linux-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          rm -rf terraform-docs.tar.gz
          chmod +x terraform-docs
          ./terraform-docs . --output-check

      - name: Setup terraform-docs with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4

      - name: Terraform init
        id: init
        run: |
          echo "Running terraform init..."
          terraform init

      - name: Render terraform docs inside for components in the README.md
        id: components-docs
        run: ./terraform-docs markdown table --config .terraform-docs-components.yml --output-mode inject --output-file README.md .

      - name: Render terraform docs inside for modules in the README.md
        id: components-modules
        run: ./terraform-docs markdown table --config .terraform-docs-modules.yml --output-mode inject --output-file README.md .

      - name: Commit changes
        id: commit
        uses: iarekylew00t/verified-bot-commit@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          if-no-commit: info
          message: "terraform-docs: automated action"
          files: |
            components/**/*.md
            modules/**/*.md
            !README.md
            !terraform-docs
```
